### ISSUE TITLE
RGB keys

### ISSUE THREAD

**Issue by jonfitt** [Envious-Data/Env-MCRO#1]
Do you think there's room for one of these on the board?
[https://www.adafruit.com/product/453](https://www.adafruit.com/product/453)

You can address 64 LEDs (enough for 12 keys * 3 RGB) using 4 pins on the Pico as an SPI interface.

I'm sure there's an SPI library already out there.

Maybe if there was a revision using a smaller board than the Pico?

**Comment by Envious-Data** [comment]
there are enough spare pins on the Raspberry pi pico, I think a better solution would be to run traces for SK6812 LEDs since you can address all of them on this board using just 3 pins and 2 of which are +5V and GND.

**Comment by Envious-Data** [comment]
Update:

Added Pads and traces for RGB LEDs, the pads fit 3535 SK6812 or WS2812**B** and also generated a gerber for LED version
in KMK you need to modify rgb.py with the right information (board.GP5 is the data pin for the LEDs)

if you order via JLCPCB you'll have to select WS2812B 3535 LEDs as they do not stock SK6812s 

its also important to make sure you have the B varient of WS2812

Enjoy 👍
