### ISSUE TITLE
PICO shuts down on key stroke.

### ISSUE THREAD

**Issue by xfatdannx** [Envious-Data/Env-MCRO#2]
I am not sure if this is an error in the script or a hardware error but the PICO seems to shut down (green LED turns off) upon first key stroke. It will stay on non-stop if no key is pressed. Have you seen this issue before?

**Comment by Envious-Data** [comment]
do you have Circuitpython 7.2.5 installed?

**Comment by xfatdannx** [comment]
Yes, everything has been installed and in working order for some time. After a resent tear down of my PC, it may have gone unused for 3-4 weeks max. Do you think it may just need to be re-flashed?

**Comment by Envious-Data** [comment]
Might be worth a try, I havent personally experienced that.
