### ISSUE TITLE
built a board but it doesn't respond to key presses

### ISSUE THREAD

**Issue by KayleaS** [Envious-Data/Env-MCRO#3]
parts used are as follows

https://www.amazon.ca/dp/B0C6FH6XQ7?ref=ppx_yo2ov_dt_b_fed_asin_title (key switches)

https://www.amazon.ca/dp/B09KVB8LVR?ref=ppx_yo2ov_dt_b_fed_asin_title (Pi Pico)

https://www.digikey.ca/en/products/detail/onsemi/1N4148/458603 (diodes) based on what is in readme

wondering if it's maybe my diodes, or if i'm doing something wrong, can provide more info if needed

**Comment by Envious-Data** [comment]
I take it you ordered the PCBs from inside the _gerber folder?

**Comment by KayleaS** [comment]
Yes

**Comment by KayleaS** [comment]
it seems i ordered the rgb version and i have no leds or the rotary encoder fitted, would that stop it from working

**Comment by Envious-Data** [comment]
Nah those shouldnt be an issue

Ive updated the QMK firmware build, the default buttons are mapped to F13 to F24 so by default they wont do anything unless you specifically map software or game buttons to them 

lemme know if all is good once you flash this.
https://github.com/Envious-Data/EnvKB-QMK/blob/main/_PREBUILTFIRMWARES/enviousdesign_mcro_rev2_default.uf2

**Comment by KayleaS** [comment]
yes it works, thanks for all the help
